swagger: "2.0"
info:
  version: "0.0.1"
  title: Broviki server
# during dev, should point to your local machine
host: localhost:8670
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /cams:
    # binds a127 app logic to a route
    x-swagger-router-controller: cams
    get:
      description: Returns list of cams to the caller
      # used as the method name of the controller
      operationId: cams
      parameters: [ ]
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CamsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  CamsResponse:
    required:
      - cams
    properties:
      cams:
        type: array
        items:
          $ref: "#/definitions/Cam"
  Cam:
    required:
      - name
      - uri
    properties:
      name:
        type: string
      uri:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
security:
  - auth:
    - cams
securityDefinitions:
  auth:
    type: oauth2
    authorizationUrl: /api/auth
    flow: implicit
    scopes:
      cams: get availible cams
